### ISSUE TITLE
Food & Hunger

### ISSUE THREAD

**Issue by martinlehoux** [martinlehoux/go-microservices#44]
## TODO

- [ ] Search for items and store in bag
- [ ] Loose energy over time
- [ ] Eat Food items to higher energy
